### ISSUE TITLE
Not right byte

### ISSUE THREAD

**Issue by JoshuaGraves28** [dsasmblr/cheat-engine#3]
when I try enabling anything such as skill points, gold key + diamond chest, ect it tells me there is an error in line 2 with the assert function. It isn't getting the right byte

**Comment by dsasmblr** [comment]
Sorry, I no longer have the time to maintain old scripts like this. I've demonstrated in videos how to find these values yourself to update the script, so give that a shot, or see if others will help you in the video comments.
