### ISSUE TITLE
Cant even activate all skrips under 1.4 Billion Golden key witch isn´t even working. So only unlimitet Ammo and health are working

### ISSUE THREAD

**Issue by BlAmEnOtMe** [dsasmblr/cheat-engine#5]

**Comment by Zepharox** [comment]
I'm also having the same issues.

**Comment by Strong1491** [comment]
indeed

**Comment by dsasmblr** [comment]
Sorry, I no longer have the time to maintain old scripts like this. I've demonstrated in videos how to find these values yourself to update the script, so give that a shot, or see if others will help you in the video comments.
