### ISSUE TITLE
Borderlands 3 CT Script Errors

### ISSUE THREAD

**Issue by JosunLP** [dsasmblr/cheat-engine#6]
When trying to use the Money, Eridium, XP and Skill Point scripts, the script crashes with the following message:

 `<<Error in line2 (assert("Borderlands3.exe"+965B42C,74 F8 8B 40 08)):The bytes at "Borderlands3.exe"+965B42C are not what was expecte>> `

It appears that the corresponding addresses cannot be determined.

**Comment by Shinta360** [comment]
i get same error

**Comment by TheSpiderDungeon** [comment]
Still an issue, March 4th
